pipeline{
    agent any
    stages{
        stage('Build'){
            steps{
                dir("HelloMaven") {
                    sh "pwd"
                    sh 'mvn clean install'
                                }

            }
        }
    }
}